id: I4DC83D77
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:54:05+00:00'
last_modified: '2022-06-08T12:48:15.815336+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18537
  title: འཚེ་མེད་ཞི་བའི་སློབ་སྟོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '5988':
      image_group_id: I1KG18542
      title: ''
      total_pages: 214
      order: 1
      base_file: 5988.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
