id: P010331
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 20:44:26.657944
source_metadata:
  id: bdr:W1KG18537
  title: འཚེ་མེད་ཞི་བའི་སློབ་སྟོན།
  author: ''
  volumes:
    0808664ab6a64a449e243ef6c31cc358:
      image_group_id: I1KG18542
      title: ''
      volume_number: 1
      total_pages: 214
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
