id: P010331
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18537
  title: འཚེ་མེད་ཞི་བའི་སློབ་སྟོན།
  author: ''
  volumes:
    0808664ab6a64a449e243ef6c31cc358:
      image_group_id: I1KG18542
      title: ''
      volume_number: 1
      total_pages: 214
